# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 966a70c5833c768590a89598093ee6c2414c944fc2bff16524eb2ca06166d8c12c0fbc1391997a54ba52a62545af3f911ebd0aa22b9dd149139dc2d5ebf64e32

test:
  secret_key_base: 798f2ef3225c8f80d1527add20caf2fd2c0b67d9958283efb8fbe29045ddd138cf3cf8c3f2cae0a40403a3f2e77d6d483a900ee0758fce934278b29e971592f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
